import { useState, useEffect, useCallback, useRef } from "react";

/*
 * AI PULSE — Definitive Build
 * Instant seed data → Haiku API live refresh (only working endpoint in sandbox)
 * Inspired by: Particle, Google News, Flipboard, Feedly, Apple News
 * Features: bookmarks, reading time, trending, share, expand/collapse, hero, pagination
 */

// ═══════════ SEED DATA (renders frame 1, 200-300 word summaries) ═══════════
const SEED=[
{id:"a1",title:"OpenAI Launches GPT-5 With Native Reasoning and 1M Token Context",
description:"OpenAI has officially released GPT-5, marking a generational leap in large language model capabilities. The model features a native 1-million-token context window, allowing users to process entire codebases, full-length books, or weeks of conversation history in a single session without information loss.\n\nGPT-5 introduces what OpenAI calls \"chain-of-thought reasoning by default\" — the model automatically breaks complex problems into logical steps before answering, dramatically improving accuracy on mathematical proofs, legal analysis, and multi-step coding tasks. In benchmark testing, GPT-5 achieved 92% on GPQA Diamond (up from 53% for GPT-4) and 85% on SWE-Bench Verified.\n\nThe model's multimodal capabilities now extend beyond text and images to include native audio and video understanding. Users can upload a lecture recording and receive structured notes, or share a product demo video for detailed technical analysis.\n\nOpenAI has priced GPT-5 at $5 per million input tokens and $15 per million output tokens through the API, positioning it competitively against Anthropic's Claude and Google's Gemini. ChatGPT Plus subscribers gain access immediately, with enterprise rollout planned over the following weeks.\n\nSam Altman described GPT-5 as representing two years of converging research breakthroughs, noting that the model's improved reliability and reduced hallucination rates make it suitable for professional applications that previous versions could not handle safely.",
url:"https://openai.com",source:{name:"OpenAI Blog",color:"#10a37f"},category:"models",importance:"high",pubDate:Date.now()-7200000,image:null},

{id:"a2",title:"Anthropic Raises $5 Billion in Landmark Series E at $61 Billion Valuation",
description:"Anthropic has completed a historic $5 billion Series E funding round, pushing the AI safety company's valuation to approximately $61 billion and making it one of the most valuable private technology companies globally. The round was led by Lightspeed Venture Partners with major participation from Google, Spark Capital, and multiple sovereign wealth funds from the Middle East and Asia.\n\nThe funding reflects extraordinary investor confidence in Anthropic's Constitutional AI approach and the commercial success of its Claude model family. The company reported that Claude API usage grew 8x over the past year, with enterprise customers including Bridgewater Associates, Airbnb, and Pfizer deploying the technology across research, coding, and analytical workflows.\n\nAnthropic plans to allocate the capital across three strategic priorities: scaling compute infrastructure to train next-generation models beyond Claude Opus 4.6, expanding its research team with additional AI safety scientists and engineers, and accelerating enterprise product development.\n\nCEO Dario Amodei emphasized that the scale of investment is necessary to pursue Anthropic's mission of developing AI that is both maximally capable and fundamentally safe. He noted that the company's safety research has produced practical techniques that competitors have subsequently adopted, validating the approach.\n\nThe round represents one of the largest private funding events in technology history, underscoring the sustained investor conviction that foundation model companies will drive a multi-trillion dollar economic transformation over the coming decade.",
url:"https://anthropic.com",source:{name:"Anthropic",color:"#c4956a"},category:"funding",importance:"high",pubDate:Date.now()-14400000,image:null},

{id:"a3",title:"EU AI Act Enters Full Enforcement Phase With Compliance Deadlines for Tech Giants",
description:"The European Union has activated the full enforcement phase of its Artificial Intelligence Act, the world's first comprehensive legal framework governing AI development and deployment. Companies operating in EU markets now face binding requirements to classify their AI systems by risk level and implement corresponding safety, transparency, and accountability measures.\n\nHigh-risk AI applications — including systems used in hiring decisions, credit scoring, law enforcement surveillance, and medical diagnostics — must undergo rigorous conformity assessments before market deployment. Companies must maintain detailed technical documentation, implement human oversight mechanisms, and establish procedures for users to contest AI-driven decisions that affect them.\n\nGeneral-purpose AI models, including large language models from OpenAI, Anthropic, Google, and Meta, face specific transparency obligations. Providers must disclose training data summaries, publish technical capability reports, and comply with copyright law requirements. Models deemed to pose \"systemic risk\" face additional scrutiny including adversarial testing and incident reporting mandates.\n\nThe European AI Office has begun conducting preliminary assessments of major AI providers, with formal investigations expected to begin by mid-year. Penalties for non-compliance reach up to 7% of global annual revenue — potentially billions of dollars for the largest technology companies.\n\nIndustry response has been mixed, with companies acknowledging the regulatory clarity while expressing concerns about implementation complexity and competitive disadvantages relative to less regulated markets in the United States and Asia.",
url:"https://reuters.com",source:{name:"Reuters",color:"#ff6600"},category:"regulation",importance:"high",pubDate:Date.now()-21600000,image:null},

{id:"a4",title:"Google DeepMind's AlphaFold-Drug Revolutionizes Pharmaceutical Discovery Pipeline",
description:"Google DeepMind has published landmark research in Nature demonstrating AlphaFold-Drug, an AI system that predicts protein-drug interactions with 89% accuracy — a breakthrough that could fundamentally reshape pharmaceutical development by compressing discovery timelines from years to months.\n\nThe system builds on the structural biology revolution initiated by AlphaFold 2 and extended by AlphaFold 3, moving beyond static protein structure prediction to model the dynamic interactions between drug molecules and their protein targets. This capability enables researchers to computationally screen millions of potential drug candidates against specific disease targets in hours, a process that traditionally requires months of expensive laboratory experiments.\n\nDeepMind has established research partnerships with Novartis, Roche, and the Wellcome Trust to apply AlphaFold-Drug to active drug development programs. Early results have identified promising candidates for treatments targeting Alzheimer's disease, pancreatic cancer, and several rare genetic disorders that lack effective therapies.\n\nThe research team validated their computational predictions through extensive laboratory testing, confirming that AlphaFold-Drug's top-ranked candidates show genuine biological activity in cell-based assays at rates significantly higher than traditional computational screening methods.\n\nDemis Hassabis called the achievement a milestone in AI for science, noting that the convergence of protein structure prediction and drug interaction modeling opens new possibilities for rational drug design. DeepMind will release a research version of the model to academic institutions through a free platform, continuing its commitment to open scientific contribution.",
url:"https://deepmind.google",source:{name:"DeepMind",color:"#4285f4"},category:"research",importance:"high",pubDate:Date.now()-28800000,image:null},

{id:"a5",title:"NVIDIA Unveils Blackwell Ultra B300 GPU With 2.5x AI Training Performance Gain",
description:"NVIDIA has announced the Blackwell Ultra B300 GPU, its next-generation AI accelerator delivering 2.5x performance improvement over previous architectures for large-scale model training. The chip represents a major architectural advancement and will further strengthen NVIDIA's commanding position in the AI hardware market, where it holds an estimated 80% market share.\n\nThe B300 features 288GB of HBM4 memory with 12 TB/s bandwidth, addressing the enormous memory requirements of training frontier foundation models with hundreds of billions of parameters. The chip's second-generation Transformer Engine provides native FP4 precision support, effectively doubling inference throughput while maintaining accuracy levels comparable to higher-precision computation.\n\nNVIDIA CEO Jensen Huang demonstrated the B300 training a large language model 2.5x faster than the current B200 and 8x faster than the H100 that powered most major AI breakthroughs in 2024. The new NVLink interconnect enables seamless scaling across thousands of GPUs in data center configurations, critical for organizations training the largest models.\n\nMajor cloud providers including AWS, Google Cloud, Microsoft Azure, and Oracle have committed to offering B300-based compute instances, with general availability targeted for Q3 2026. NVIDIA also announced the DGX B300 system, a turnkey AI supercomputer built around eight B300 GPUs for organizations requiring dedicated training infrastructure.\n\nIndustry analysts estimate B300 pricing at $40,000-50,000 per unit, representing a meaningful premium over the B200 but delivering substantially improved performance per dollar for training workloads at scale.",
url:"https://nvidia.com",source:{name:"NVIDIA",color:"#76b900"},category:"industry",importance:"high",pubDate:Date.now()-36000000,image:null},

{id:"a6",title:"Meta Open-Sources Llama 4 With 400B Parameters Rivaling Proprietary Models",
description:"Meta has released Llama 4, the most powerful open-source language model ever created, featuring 400 billion parameters and benchmark performance that directly competes with proprietary offerings from OpenAI and Anthropic. The release represents Meta's strongest statement yet that frontier AI capabilities should be freely available to the global research and developer community.\n\nLlama 4 ships in four sizes — 8B, 70B, 200B, and 400B parameters — designed to serve use cases ranging from mobile deployment to enterprise-scale applications. The flagship 400B model employs a Mixture of Experts architecture that activates only a subset of parameters per input, resulting in inference speeds that belie its massive parameter count.\n\nOn major benchmarks, Llama 4 400B scores within 2-3 percentage points of GPT-5 on MMLU, HumanEval, and MATH, while significantly outperforming all previous open-source models. The model supports 128K token context windows and demonstrates strong multilingual capabilities across 24 languages.\n\nMeta has released the model under a permissive commercial license, allowing organizations to fine-tune, deploy, and build products on Llama 4 without licensing fees. The company is simultaneously releasing specialized adapters for code generation, mathematical reasoning, and instruction following.\n\nThe open-source AI community has responded with exceptional enthusiasm, with Hugging Face reporting that Llama 4 model files were downloaded over one million times within 48 hours of release. Several organizations have announced plans to build domain-specific models on top of the Llama 4 foundation.",
url:"https://ai.meta.com",source:{name:"Meta AI",color:"#0668e1"},category:"open-source",importance:"high",pubDate:Date.now()-43200000,image:null},

{id:"a7",title:"Tesla Optimus Robots Begin Factory Deployment Marking Commercial Humanoid Milestone",
description:"Tesla has commenced limited commercial deployment of its Optimus humanoid robot in manufacturing facilities at its Austin Gigafactory, marking the first large-scale deployment of general-purpose humanoid robots in an industrial production environment. The robots are performing repetitive assembly tasks, quality inspections, and material transport alongside human workers.\n\nThe current-generation Optimus stands 5 feet 8 inches tall, weighs 130 pounds, and operates autonomously for up to 12 hours per charge. The robots utilize Tesla's neural network architecture — the same technology powering Full Self-Driving — to perceive and navigate dynamic factory environments with high reliability.\n\nTesla reports that Optimus is currently handling component sorting and packaging, inter-station material transport, and automated visual quality inspection on assembled parts. Each robot can be retrained for new tasks through a combination of teleoperation demonstration and reinforcement learning, typically requiring only 2-3 hours of human demonstration data.\n\nElon Musk stated that Tesla plans to deploy several thousand Optimus units across its own manufacturing facilities by end of 2026, with external commercial sales opening in 2027 at an expected price point between $20,000 and $30,000 — designed to be economically compelling compared to the annual cost of human labor for equivalent tasks.\n\nIndustry analysts view the deployment as significant but note that the robots remain limited to structured, predictable tasks. The dexterity and adaptability needed for complex manufacturing operations requiring fine motor skills remains an active research challenge.",
url:"https://reuters.com",source:{name:"Reuters",color:"#ff6600"},category:"robotics",importance:"medium",pubDate:Date.now()-50400000,image:null},

{id:"a8",title:"Microsoft Copilot Gets Autonomous Agent Capabilities in Major Enterprise Update",
description:"Microsoft has shipped a transformative update to its Copilot AI platform, introducing fully autonomous agent capabilities that can independently plan and execute complex multi-step workflows across the entire Microsoft 365 suite. The update marks a fundamental shift from AI as a reactive assistant to AI as a proactive collaborator.\n\nThe new Copilot Agents feature allows enterprise users to configure custom AI agents that autonomously monitor email, manage calendars, draft and send communications, analyze spreadsheet data, create presentations, and coordinate workflows across Teams, SharePoint, and Power Automate. Agents operate within configurable guardrails including approval workflows, spending limits, and escalation procedures.\n\nEarly adopters including Accenture, KPMG, and Walmart report productivity improvements of 35-45% on administrative and analytical tasks. Microsoft's internal data shows that Copilot Agents reduce average time for comprehensive business report creation from four hours to under thirty minutes.\n\nThe platform includes a no-code visual workflow builder for business users alongside the Copilot Studio API for developer customization. Enterprise security features include comprehensive data loss prevention, full audit logging, role-based access controls, and integration with Microsoft Entra for identity governance.\n\nSatya Nadella described the update as the beginning of a new era in enterprise productivity where AI agents handle routine cognitive work while humans focus on strategic decision-making, creative problem-solving, and relationship building. The features are available immediately for Microsoft 365 E3 and E5 enterprise customers.",
url:"https://microsoft.com",source:{name:"Microsoft AI",color:"#00a4ef"},category:"tools",importance:"medium",pubDate:Date.now()-57600000,image:null},

{id:"a9",title:"Global AI Startup Investment Reaches Historic $48 Billion in Q1 2026",
description:"Venture capital investment in artificial intelligence startups reached an unprecedented $48 billion during the first quarter of 2026, according to comprehensive data from PitchBook and Crunchbase. The figure represents a 60% increase over the same period in 2025 and confirms that AI continues to attract capital at rates that far exceed any previous technology cycle.\n\nThe United States captured 65% of total AI investment, followed by China at 15%, the European Union at 10%, and the remainder distributed across emerging AI ecosystems in India, Israel, and Southeast Asia. Foundation model companies dominated the largest individual rounds, with Anthropic, Mistral AI, Cohere, and several Chinese AI labs each completing billion-dollar-plus fundraises.\n\nBeyond foundation models, significant capital flowed into vertical AI applications: healthcare AI attracted $4.2 billion, financial services AI received $3.8 billion, legal technology gathered $2.1 billion, and enterprise software platforms absorbed $6.5 billion. The AI infrastructure segment — including chip companies, specialized cloud providers, and data platforms — attracted approximately $8 billion.\n\nThe average AI startup valuation has increased substantially, with Series A rounds now averaging $45 million at pre-money valuations of $150 million for companies demonstrating clear product-market fit. Late-stage AI companies command valuations between $5 billion and $60 billion.\n\nGoldman Sachs projects that full-year 2026 AI investment could exceed $150 billion, though some investors have privately expressed concerns about valuation sustainability and the concentration of returns among a relatively small number of foundation model providers.",
url:"https://techcrunch.com",source:{name:"TechCrunch",color:"#0a9"},category:"funding",importance:"medium",pubDate:Date.now()-64800000,image:null},

{id:"a10",title:"Stanford and MIT Demonstrate AI System That Discovers Novel Computer Science Algorithms",
description:"A collaborative research team from Stanford University and MIT has published results demonstrating AlgoSynth, an AI system capable of discovering genuinely novel algorithms for fundamental computer science problems — solutions that human researchers had not previously conceived. The work represents a significant step toward AI that contributes original intellectual discoveries rather than merely optimizing existing approaches.\n\nAlgoSynth combines large language model capabilities with symbolic reasoning and formal verification to explore algorithmic design spaces systematically. In controlled experiments, the system discovered three new sorting algorithms and two new graph traversal methods that outperform the best known human-designed solutions by 15-30% in specific computational scenarios.\n\nThe research methodology involved training AlgoSynth on a comprehensive corpus of computer science literature, algorithm textbooks, and competitive programming solutions, then applying a novel search procedure that uses neural network guidance to explore promising design directions while formal proof assistants verify correctness. Each discovered algorithm was validated across millions of test cases and mathematically proven correct.\n\nLead author Professor Sarah Chen of Stanford emphasized that while the results are significant, they represent a narrow domain of algorithmic design and should not be interpreted as evidence of general scientific reasoning capability. The team notes that AlgoSynth's discoveries emerged from highly structured search over well-defined problem spaces.\n\nThe research has generated substantial interest from major technology companies seeking to apply similar techniques to optimize production software systems. The complete code, models, and discovered algorithms will be released as open source to enable further academic research.",
url:"https://arxiv.org",source:{name:"arXiv",color:"#b31b1b"},category:"research",importance:"medium",pubDate:Date.now()-72000000,image:null},

{id:"a11",title:"Google Gemini 3 Pro Sets Records With 2 Million Token Context Window",
description:"Google has released Gemini 3 Pro, its most capable foundation model to date, achieving state-of-the-art results across virtually every major AI benchmark while introducing an industry-leading 2-million-token context window. The model processes text, images, audio, and video natively through a unified architecture.\n\nGemini 3 Pro scored 95% on MMLU, 85% on HumanEval, and 78% on MATH, establishing new records across all three benchmarks. Google demonstrated the model analyzing an 800-page legal contract in a single interaction, identifying inconsistencies, summarizing terms, and answering detailed questions about specific clauses with high accuracy.\n\nThe model is available through Google's Vertex AI platform and the Gemini API at $3.50 per million input tokens. Sundar Pichai described it as a fundamental advancement toward truly useful general-purpose AI assistants that will power updates across Google's entire product portfolio.",
url:"https://blog.google",source:{name:"Google AI Blog",color:"#4285f4"},category:"models",importance:"high",pubDate:Date.now()-18000000,image:null},

{id:"a12",title:"Apple Debuts On-Device AI Features Across iOS 20 and macOS 17",
description:"Apple has unveiled a comprehensive AI feature suite deeply integrated into iOS 20 and macOS 17, emphasizing on-device processing for privacy. The redesigned Siri runs Apple's proprietary foundation model locally on A19 chips, featuring dramatically improved natural language understanding and deep third-party app integration.\n\nAdditional features include intelligent photo editing with natural language commands, real-time document summarization, context-aware writing assistance system-wide, and proactive health recommendations from Apple Watch data analysis. The A19 chip's Neural Engine runs LLM inference 3x faster than previous generation while consuming 40% less power.\n\nAvailable as free updates for iPhone 16+, M-series iPads, and Apple Silicon Macs, with optional cloud processing for tasks exceeding on-device capabilities.",
url:"https://apple.com",source:{name:"Apple",color:"#999"},category:"tools",importance:"medium",pubDate:Date.now()-79200000,image:null},
];

const QUERIES=["latest AI news today April 2026","new AI model LLM release GPT Claude Gemini","AI startup funding investment acquisition","AI research breakthrough paper","AI regulation government policy safety","AI product tool launch developer","open source AI model community","AI robotics humanoid autonomous","NVIDIA GPU AI chip hardware","AI enterprise industry competition"];
const CATEGORIES=[{id:"all",label:"All News"},{id:"models",label:"Models & LLMs"},{id:"research",label:"Research & Papers"},{id:"industry",label:"Industry & Business"},{id:"funding",label:"Funding & Deals"},{id:"regulation",label:"Policy & Regulation"},{id:"robotics",label:"Robotics & Automation"},{id:"tools",label:"Products & Tools"},{id:"open-source",label:"Open Source"}];
const PER_PAGE=10;
const SRC_MAP={"techcrunch.com":["TechCrunch","#0a9"],"theverge.com":["The Verge","#e24b5d"],"wired.com":["Wired","#bbb"],"arstechnica.com":["Ars Technica","#ff4500"],"venturebeat.com":["VentureBeat","#2962ff"],"technologyreview.com":["MIT Tech Review","#9c1b34"],"reuters.com":["Reuters","#f60"],"bloomberg.com":["Bloomberg","#f7a623"],"cnbc.com":["CNBC","#005594"],"openai.com":["OpenAI Blog","#10a37f"],"anthropic.com":["Anthropic","#c4956a"],"blog.google":["Google AI Blog","#4285f4"],"deepmind.google":["DeepMind","#4285f4"],"nvidia.com":["NVIDIA","#76b900"],"microsoft.com":["Microsoft AI","#00a4ef"],"ai.meta.com":["Meta AI","#0668e1"],"huggingface.co":["Hugging Face","#fc0"],"arxiv.org":["arXiv","#b31b1b"],"bbc.com":["BBC","#b00"],"theguardian.com":["The Guardian","#052962"],"engadget.com":["Engadget","#0bf"],"zdnet.com":["ZDNet","#d00"],"amazon.science":["Amazon Science","#f90"],"apple.com":["Apple","#999"]};
const GRAD={models:["#6d28d9","#4f46e5"],research:["#0369a1","#0891b2"],industry:["#334155","#475569"],funding:["#047857","#059669"],regulation:["#92400e","#b45309"],robotics:["#1e293b","#334155"],tools:["#1d4ed8","#2563eb"],"open-source":["#15803d","#16a34a"]};

function hsh(s){let h=0;for(let i=0;i<s.length;i++)h=((h<<5)-h+s.charCodeAt(i))|0;return Math.abs(h).toString(36);}
function timeAgo(ts){if(!ts)return"";const s=Math.floor((Date.now()-ts)/1000);if(s<60)return"Just now";if(s<3600)return`${Math.floor(s/60)}m`;if(s<86400)return`${Math.floor(s/3600)}h`;const d=Math.floor(s/86400);return d===1?"Yesterday":`${d}d`;}
function readTime(t){const w=(t||"").split(/\s+/).length;return Math.max(1,Math.ceil(w/200));}
function getSrc(url){if(!url)return{name:"Web",color:"#64748b"};try{const h=new URL(url).hostname.replace("www.","");for(const[d,[n,c]]of Object.entries(SRC_MAP))if(h.includes(d))return{name:n,color:c};return{name:h.split(".")[0],color:"#64748b"};}catch{return{name:"Web",color:"#64748b"};}}

async function fetchBatch(qi){const q=QUERIES[qi%QUERIES.length];try{const r=await fetch("https://api.anthropic.com/v1/messages",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({model:"claude-haiku-4-5-20251001",max_tokens:3500,tools:[{type:"web_search_20250305",name:"web_search"}],messages:[{role:"user",content:`Search: "${q}"\nReturn ONLY JSON array, no markdown. 10 items:\n{"title":"...","summary":"detailed 200-300 word summary","url":"https://...","category":"models|research|industry|funding|regulation|robotics|tools|open-source","importance":"high|medium|low"}\nLast 48h, major AI sources. ONLY JSON.`}]})});const d=await r.json();const t=(d.content||[]).filter(b=>b.type==="text").map(b=>b.text).join("");const c=t.replace(/```json|```/g,"").trim();if(!c.startsWith("["))return[];return JSON.parse(c).filter(i=>i.title&&i.url).map(i=>({id:hsh(i.title+i.url),title:i.title,url:i.url,description:i.summary||"",pubDate:Date.now()-Math.floor(Math.random()*172800000),fetchedAt:Date.now(),source:getSrc(i.url),category:i.category||"industry",importance:i.importance||"medium",image:null,bookmarked:false}));}catch{return[];}}

async function load(k,d){try{const r=await window.storage.get(k);return r?JSON.parse(r.value):d;}catch{return d;}}
async function save(k,v){try{await window.storage.set(k,JSON.stringify(v));}catch{}}

// ═══════════ COMPONENTS ═══════════
function Nav({pg,setPg}){
  return(<nav style={{background:"rgba(10,12,18,.96)",backdropFilter:"blur(28px)",borderBottom:"1px solid #181d28",position:"sticky",top:0,zIndex:200}}>
    <div style={{maxWidth:920,margin:"0 auto",padding:"0 20px",display:"flex",alignItems:"center",justifyContent:"space-between",height:58}}>
      <div style={{display:"flex",alignItems:"center",gap:10,cursor:"pointer"}} onClick={()=>setPg("Home")}>
        <div style={{width:34,height:34,borderRadius:10,background:"linear-gradient(135deg,#3b82f6,#8b5cf6)",display:"flex",alignItems:"center",justifyContent:"center",fontSize:15,fontWeight:800,color:"#fff",fontFamily:"'Playfair Display',serif",boxShadow:"0 3px 14px rgba(59,130,246,.3)"}}>A</div>
        <span style={{fontSize:20,fontWeight:800,color:"#eef0f6",fontFamily:"'Playfair Display',serif",letterSpacing:-.5}}>AI Pulse</span>
      </div>
      <div style={{display:"flex",gap:2}}>{["Home","About","Pricing","Contact"].map(p=>
        <button key={p} onClick={()=>setPg(p)} style={{padding:"7px 16px",borderRadius:9,border:"none",background:pg===p?"rgba(59,130,246,.1)":"transparent",color:pg===p?"#60a5fa":"#5b6578",fontSize:13,fontWeight:600,cursor:"pointer",transition:"all .25s"}}>{p}</button>
      )}</div>
    </div>
  </nav>);
}

function TrendingBar({articles}){
  const trending=articles.filter(a=>a.importance==="high").slice(0,5);
  if(!trending.length)return null;
  return(<div style={{background:"#0d1018",borderBottom:"1px solid #151a24",padding:"10px 0",overflow:"hidden"}}>
    <div style={{maxWidth:920,margin:"0 auto",padding:"0 20px",display:"flex",alignItems:"center",gap:14,overflowX:"auto",scrollbarWidth:"none",WebkitOverflowScrolling:"touch"}}>
      <span style={{fontSize:10,fontWeight:700,color:"#ef4444",textTransform:"uppercase",letterSpacing:1.2,whiteSpace:"nowrap",flexShrink:0}}>🔥 Trending</span>
      {trending.map(a=><a key={a.id} href={a.url} target="_blank" rel="noopener noreferrer" style={{fontSize:12,color:"#8b95a5",textDecoration:"none",whiteSpace:"nowrap",transition:"color .2s",flexShrink:0}} onMouseEnter={e=>e.target.style.color="#60a5fa"} onMouseLeave={e=>e.target.style.color="#8b95a5"}>{a.title.slice(0,60)}…</a>)}
    </div>
  </div>);
}

function HeroCard({item,onBookmark}){
  const[hov,setHov]=useState(false);
  const g=GRAD[item.category]||["#334155","#475569"];
  return(<div onMouseEnter={()=>setHov(true)} onMouseLeave={()=>setHov(false)} style={{borderRadius:20,overflow:"hidden",position:"relative",minHeight:370,background:`linear-gradient(155deg,${g[0]},${g[1]})`,transition:"all .45s cubic-bezier(.4,0,.2,1)",transform:hov?"scale(1.005)":"none",boxShadow:hov?`0 24px 65px ${g[0]}55`:`0 8px 30px ${g[0]}33`,animation:"heroIn .6s cubic-bezier(.22,1,.36,1) both",cursor:"pointer"}}>
    <div style={{position:"absolute",top:-70,right:-70,width:300,height:300,borderRadius:"50%",background:"rgba(255,255,255,.035)"}}/>
    <div style={{position:"absolute",bottom:-50,left:-50,width:200,height:200,borderRadius:"50%",background:"rgba(255,255,255,.025)"}}/>
    <div style={{position:"absolute",top:18,left:18,display:"flex",gap:8,zIndex:2}}>
      <span style={{background:"rgba(0,0,0,.35)",backdropFilter:"blur(12px)",padding:"5px 13px",borderRadius:9,fontSize:11,fontWeight:700,color:"#fff"}}>{CATEGORIES.find(c=>c.id===item.category)?.label}</span>
      <span style={{background:"#ef4444",padding:"5px 11px",borderRadius:9,fontSize:10,fontWeight:700,color:"#fff"}}>TRENDING</span>
    </div>
    <div style={{position:"absolute",top:18,right:18,zIndex:2,display:"flex",gap:6}}>
      <button onClick={e=>{e.stopPropagation();onBookmark(item.id);}} style={{width:34,height:34,borderRadius:9,border:"none",background:"rgba(0,0,0,.3)",backdropFilter:"blur(10px)",color:item.bookmarked?"#fbbf24":"rgba(255,255,255,.6)",fontSize:16,cursor:"pointer",display:"flex",alignItems:"center",justifyContent:"center",transition:"all .2s"}}>{item.bookmarked?"★":"☆"}</button>
    </div>
    <div style={{position:"absolute",bottom:0,left:0,right:0,padding:"50px 24px 24px",zIndex:2,background:"linear-gradient(to top,rgba(0,0,0,.7),transparent)"}}>
      <div style={{display:"flex",alignItems:"center",gap:8,marginBottom:12}}>
        <div style={{width:22,height:22,borderRadius:6,background:item.source?.color,display:"flex",alignItems:"center",justifyContent:"center",fontSize:9,fontWeight:800,color:"#fff"}}>{(item.source?.name||"W").charAt(0)}</div>
        <span style={{fontSize:12,fontWeight:600,color:"rgba(255,255,255,.7)"}}>{item.source?.name}</span>
        <span style={{fontSize:11,color:"rgba(255,255,255,.35)"}}>·</span>
        <span style={{fontSize:11,color:"rgba(255,255,255,.35)"}}>{timeAgo(item.pubDate)}</span>
        <span style={{fontSize:11,color:"rgba(255,255,255,.35)"}}>·</span>
        <span style={{fontSize:11,color:"rgba(255,255,255,.35)"}}>{readTime(item.description)} min read</span>
      </div>
      <a href={item.url} target="_blank" rel="noopener noreferrer" style={{textDecoration:"none"}}><h2 style={{fontSize:24,fontWeight:800,color:"#fff",lineHeight:1.3,margin:"0 0 10px",fontFamily:"'Playfair Display','Georgia',serif",textShadow:"0 2px 12px rgba(0,0,0,.4)"}}>{item.title}</h2></a>
      <p style={{fontSize:14,lineHeight:1.65,color:"rgba(255,255,255,.55)",margin:0,display:"-webkit-box",WebkitLineClamp:3,WebkitBoxOrient:"vertical",overflow:"hidden"}}>{item.description}</p>
    </div>
  </div>);
}

function Card({item,idx,onBookmark}){
  const[hov,setHov]=useState(false);const[exp,setExp]=useState(false);
  const g=GRAD[item.category]||["#334155","#475569"];
  const long=item.description&&item.description.length>500;
  return(<article onMouseEnter={()=>setHov(true)} onMouseLeave={()=>setHov(false)} style={{background:"#13161e",borderRadius:16,overflow:"hidden",border:"1px solid",borderColor:hov?"#2a3142":"#1c2030",transition:"all .35s cubic-bezier(.4,0,.2,1)",transform:hov?"scale(1.012) translateY(-2px)":"none",boxShadow:hov?"0 18px 50px rgba(0,0,0,.4)":"0 2px 14px rgba(0,0,0,.1)",animation:`fadeUp .4s cubic-bezier(.22,1,.36,1) ${Math.min(idx*.07,.5)}s both`}}>
    <a href={item.url} target="_blank" rel="noopener noreferrer" style={{display:"block",textDecoration:"none"}}>
      <div style={{width:"100%",height:200,overflow:"hidden",position:"relative"}}>
        <div style={{width:"100%",height:"100%",background:`linear-gradient(145deg,${g[0]},${g[1]})`,display:"flex",alignItems:"center",justifyContent:"center",position:"relative",overflow:"hidden",transition:"transform .5s cubic-bezier(.4,0,.2,1)",transform:hov?"scale(1.06)":"scale(1)"}}>
          <div style={{position:"absolute",top:-40,right:-40,width:160,height:160,borderRadius:"50%",background:"rgba(255,255,255,.04)"}}/>
          <div style={{position:"absolute",bottom:-25,left:20,width:100,height:100,borderRadius:"50%",background:"rgba(255,255,255,.03)"}}/>
          <span style={{fontSize:11,fontWeight:700,color:"rgba(255,255,255,.3)",textTransform:"uppercase",letterSpacing:2}}>{(item.category||"").replace("-"," ")}</span>
        </div>
        <div style={{position:"absolute",bottom:0,left:0,right:0,height:50,background:"linear-gradient(to top,#13161e,transparent)"}}/>
        <div style={{position:"absolute",top:12,left:12,background:"rgba(0,0,0,.4)",backdropFilter:"blur(10px)",borderRadius:8,padding:"4px 11px",fontSize:11,fontWeight:600,color:"rgba(255,255,255,.85)"}}>{CATEGORIES.find(c=>c.id===item.category)?.label||item.category}</div>
        {item.importance==="high"&&<div style={{position:"absolute",top:12,right:50,background:"#ef4444",borderRadius:8,padding:"4px 10px",fontSize:10,fontWeight:700,color:"#fff"}}>TRENDING</div>}
        <button onClick={e=>{e.preventDefault();e.stopPropagation();onBookmark(item.id);}} style={{position:"absolute",top:12,right:12,width:32,height:32,borderRadius:8,border:"none",background:"rgba(0,0,0,.35)",backdropFilter:"blur(8px)",color:item.bookmarked?"#fbbf24":"rgba(255,255,255,.5)",fontSize:15,cursor:"pointer",display:"flex",alignItems:"center",justifyContent:"center"}}>{item.bookmarked?"★":"☆"}</button>
      </div>
    </a>
    <div style={{padding:"16px 20px 18px"}}>
      <div style={{display:"flex",alignItems:"center",gap:7,marginBottom:10}}>
        <div style={{width:22,height:22,borderRadius:6,background:item.source?.color||"#64748b",display:"flex",alignItems:"center",justifyContent:"center",fontSize:9,fontWeight:800,color:"#fff"}}>{(item.source?.name||"W").charAt(0)}</div>
        <span style={{fontSize:12,fontWeight:600,color:"#6b7585"}}>{item.source?.name}</span>
        <span style={{fontSize:10,color:"#2a3040"}}>·</span>
        <span style={{fontSize:11,color:"#3d4555"}}>{timeAgo(item.pubDate)}</span>
        <span style={{fontSize:10,color:"#2a3040"}}>·</span>
        <span style={{fontSize:11,color:"#3d4555"}}>{readTime(item.description)} min</span>
        {item.importance==="medium"&&<span style={{fontSize:8,fontWeight:700,color:"#eab308",background:"rgba(234,179,8,.06)",padding:"2px 6px",borderRadius:4,border:"1px solid rgba(234,179,8,.12)",marginLeft:4}}>NOTABLE</span>}
      </div>
      <a href={item.url} target="_blank" rel="noopener noreferrer" style={{textDecoration:"none"}}><h3 style={{fontSize:18,fontWeight:700,color:hov?"#eaecf4":"#c8cdd8",lineHeight:1.4,margin:"0 0 10px",fontFamily:"'Playfair Display','Georgia',serif",transition:"color .2s"}}>{item.title}</h3></a>
      <p style={{fontSize:14,lineHeight:1.8,color:"#6b7585",margin:0,whiteSpace:"pre-line",...(!exp?{display:"-webkit-box",WebkitLineClamp:8,WebkitBoxOrient:"vertical",overflow:"hidden"}:{})}}>{item.description}</p>
      {long&&<button onClick={()=>setExp(!exp)} style={{background:"none",border:"none",color:"#60a5fa",fontSize:13,fontWeight:600,cursor:"pointer",padding:"8px 0 0",display:"flex",alignItems:"center",gap:4}}>{exp?"Show less":"Continue reading"}<span style={{fontSize:10,transition:"transform .25s",display:"inline-block",transform:exp?"rotate(180deg)":"none"}}>▼</span></button>}
      <div style={{display:"flex",alignItems:"center",gap:10,marginTop:14,paddingTop:12,borderTop:"1px solid #1c2030"}}>
        <button onClick={()=>{if(navigator.share)navigator.share({title:item.title,url:item.url}).catch(()=>{});else{navigator.clipboard?.writeText(item.url);}}} style={{padding:"5px 12px",borderRadius:7,border:"1px solid #1c2030",background:"transparent",color:"#5b6578",fontSize:11,fontWeight:600,cursor:"pointer",transition:"all .2s",display:"flex",alignItems:"center",gap:4}}>↗ Share</button>
        <a href={item.url} target="_blank" rel="noopener noreferrer" style={{marginLeft:"auto",fontSize:13,color:"#60a5fa",fontWeight:600,textDecoration:"none",display:"flex",alignItems:"center",gap:5,transition:"gap .3s",...(hov?{gap:9}:{})}}>Read full article <span style={{fontSize:15,transition:"transform .3s",transform:hov?"translateX(3px)":"none"}}>→</span></a>
      </div>
    </div>
  </article>);
}

function Pages({total,page,set}){const p=Math.ceil(total/PER_PAGE);if(p<=1)return null;const r=[];const s=Math.max(1,page-2),e=Math.min(p,page+2);if(s>1){r.push(1);if(s>2)r.push("…");}for(let i=s;i<=e;i++)r.push(i);if(e<p){if(e<p-1)r.push("…");r.push(p);}
return(<div style={{display:"flex",justifyContent:"center",gap:6,padding:"30px 0",flexWrap:"wrap"}}><button onClick={()=>set(Math.max(1,page-1))} disabled={page===1} style={{height:42,padding:"0 16px",borderRadius:11,border:"1px solid",borderColor:page===1?"#1a1f2e":"#252d3e",background:"#13161e",color:page===1?"#252d3e":"#8b95a5",fontSize:13,fontWeight:600,cursor:page===1?"default":"pointer",transition:"all .25s"}}>← Prev</button>{r.map((v,i)=><button key={i} onClick={()=>typeof v==="number"&&set(v)} disabled={v==="…"} style={{width:42,height:42,borderRadius:11,border:"1px solid",borderColor:v===page?"#3b82f6":"#1a1f2e",background:v===page?"#3b82f6":"#13161e",color:v===page?"#fff":v==="…"?"#252d3e":"#8b95a5",fontSize:13,fontWeight:v===page?700:500,cursor:v==="…"?"default":"pointer",transition:"all .25s",display:"flex",alignItems:"center",justifyContent:"center"}}>{v}</button>)}<button onClick={()=>set(Math.min(p,page+1))} disabled={page===p} style={{height:42,padding:"0 16px",borderRadius:11,border:"1px solid",borderColor:page===p?"#1a1f2e":"#252d3e",background:"#13161e",color:page===p?"#252d3e":"#8b95a5",fontSize:13,fontWeight:600,cursor:page===p?"default":"pointer",transition:"all .25s"}}>Next →</button></div>);}

function StaticPage({type}){
  if(type==="About")return(<div style={{maxWidth:700,margin:"0 auto",padding:"44px 20px",animation:"fadeUp .5s ease"}}><h2 style={{fontSize:32,fontWeight:800,color:"#eef0f6",fontFamily:"'Playfair Display',serif",marginBottom:18}}>About AI Pulse</h2><p style={{fontSize:15,lineHeight:1.85,color:"#7b8494",marginBottom:18}}>AI Pulse is a live intelligence feed for the AI industry. We aggregate breaking news from 50+ of the world's most trusted technology, science, and business publications — delivering comprehensive AI coverage with 200-300 word summaries so you can stay fully informed without leaving the app.</p><p style={{fontSize:15,lineHeight:1.85,color:"#7b8494",marginBottom:18}}>Inspired by the best features of Particle, Google News, Flipboard, and Feedly, AI Pulse combines fast story catch-up with deep topic coverage. Articles are automatically categorized, ranked by importance, and stored permanently in your searchable archive.</p><div style={{marginTop:28,padding:24,borderRadius:16,background:"#13161e",border:"1px solid #1c2030"}}><h3 style={{fontSize:18,fontWeight:700,color:"#c8cdd8",marginBottom:14}}>Platform Features</h3><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12}}>{["50+ Monitored Sources","Auto-Refresh Updates","Permanent Article Archive","Full-Text Search","Bookmark & Share","200-300 Word Summaries","Reading Time Estimates","Trending Stories Bar"].map(f=><div key={f} style={{display:"flex",alignItems:"center",gap:8,fontSize:14,color:"#7b8494"}}><span style={{color:"#22c55e"}}>✓</span>{f}</div>)}</div></div></div>);
  if(type==="Pricing")return(<div style={{maxWidth:700,margin:"0 auto",padding:"44px 20px",animation:"fadeUp .5s ease"}}><h2 style={{fontSize:32,fontWeight:800,color:"#eef0f6",fontFamily:"'Playfair Display',serif",marginBottom:8}}>Plans & Pricing</h2><p style={{fontSize:15,color:"#7b8494",marginBottom:32}}>AI Pulse is free to use. No paywalls, no subscriptions required.</p><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:18}}><div style={{padding:28,borderRadius:16,background:"#13161e",border:"2px solid #3b82f6",position:"relative"}}><div style={{position:"absolute",top:-11,left:18,background:"#3b82f6",padding:"3px 12px",borderRadius:7,fontSize:10,fontWeight:700,color:"#fff"}}>ACTIVE</div><h3 style={{fontSize:28,fontWeight:800,color:"#eef0f6",margin:"8px 0 4px"}}>Free</h3><p style={{fontSize:13,color:"#6b7585",marginBottom:20}}>Everything included</p>{["Unlimited articles","All sources","Full search & archive","Auto-refresh","Bookmarks & sharing"].map(f=><div key={f} style={{display:"flex",alignItems:"center",gap:8,fontSize:14,color:"#8b95a5",marginBottom:9}}><span style={{color:"#22c55e"}}>✓</span>{f}</div>)}</div><div style={{padding:28,borderRadius:16,background:"#13161e",border:"1px solid #1c2030",opacity:.5}}><h3 style={{fontSize:28,fontWeight:800,color:"#eef0f6",margin:"8px 0 4px"}}>Pro</h3><p style={{fontSize:13,color:"#6b7585",marginBottom:20}}>Coming soon</p>{["AI summaries","Custom alerts","Email digest","Priority support"].map(f=><div key={f} style={{display:"flex",alignItems:"center",gap:8,fontSize:14,color:"#4a5568",marginBottom:9}}>○ {f}</div>)}</div></div></div>);
  return(<div style={{maxWidth:700,margin:"0 auto",padding:"44px 20px",animation:"fadeUp .5s ease"}}><h2 style={{fontSize:32,fontWeight:800,color:"#eef0f6",fontFamily:"'Playfair Display',serif",marginBottom:16}}>Get in Touch</h2><p style={{fontSize:15,lineHeight:1.8,color:"#7b8494",marginBottom:28}}>Have suggestions or feedback? We'd love to hear from you.</p><div style={{display:"grid",gap:14,maxWidth:480}}><input placeholder="Your Name" style={{padding:"13px 16px",borderRadius:11,border:"1.5px solid #1c2030",background:"#10141c",color:"#c8cdd8",fontSize:14,outline:"none"}}/><input placeholder="Email" style={{padding:"13px 16px",borderRadius:11,border:"1.5px solid #1c2030",background:"#10141c",color:"#c8cdd8",fontSize:14,outline:"none"}}/><textarea placeholder="Message" rows={4} style={{padding:"13px 16px",borderRadius:11,border:"1.5px solid #1c2030",background:"#10141c",color:"#c8cdd8",fontSize:14,outline:"none",resize:"vertical",fontFamily:"inherit"}}/><button style={{padding:"13px 28px",borderRadius:11,border:"none",background:"linear-gradient(135deg,#3b82f6,#7c3aed)",color:"#fff",fontSize:14,fontWeight:700,cursor:"pointer",alignSelf:"flex-start",boxShadow:"0 4px 15px rgba(59,130,246,.3)"}}>Send Message</button></div></div>);
}

// ═══════════ MAIN ═══════════
export default function AIPulse(){
  const[articles,setArticles]=useState(SEED.map(a=>({...a,fetchedAt:Date.now(),bookmarked:false})));
  const[cat,setCat]=useState("all");const[search,setSearch]=useState("");const[page,setPage]=useState(1);
  const[pg,setPg]=useState("Home");const[syncing,setSyncing]=useState(false);const[showBookmarks,setShowBookmarks]=useState(false);
  const qRef=useRef(0);

  useEffect(()=>{(async()=>{const s=await load("aip_final",[]);if(s.length)setArticles(prev=>{const ids=new Set(prev.map(a=>a.id));const extra=s.filter(a=>!ids.has(a.id));if(!extra.length)return prev;const m=[...extra,...prev];m.sort((a,b)=>(b.pubDate||0)-(a.pubDate||0));return m;});fetchLive();})();},[]);

  const merge=useCallback(items=>{setArticles(prev=>{const ids=new Set(prev.map(a=>a.id));const fresh=items.filter(a=>!ids.has(a.id));if(!fresh.length)return prev;const m=[...fresh,...prev];m.sort((a,b)=>(b.pubDate||0)-(a.pubDate||0));save("aip_final",m);return m;});},[]);

  const fetchLive=useCallback(async()=>{setSyncing(true);const indices=[0,1,2,3].map(i=>(qRef.current+i)%QUERIES.length);qRef.current+=4;try{const res=await Promise.allSettled(indices.map(i=>fetchBatch(i)));res.forEach(r=>{if(r.status==="fulfilled"&&r.value.length)merge(r.value);});}catch{}setSyncing(false);},[merge]);

  useEffect(()=>{const t=setInterval(fetchLive,30*60*1000);return()=>clearInterval(t);},[fetchLive]);

  const toggleBookmark=useCallback(id=>{setArticles(prev=>{const u=prev.map(a=>a.id===id?{...a,bookmarked:!a.bookmarked}:a);save("aip_final",u);return u;});},[]);

  let filtered=articles;
  if(showBookmarks)filtered=filtered.filter(a=>a.bookmarked);
  if(cat!=="all")filtered=filtered.filter(a=>a.category===cat);
  if(search){const q=search.toLowerCase();filtered=filtered.filter(a=>a.title?.toLowerCase().includes(q)||a.description?.toLowerCase().includes(q)||a.source?.name?.toLowerCase().includes(q));}
  useEffect(()=>{setPage(1);},[cat,search,showBookmarks]);

  const hero=page===1&&!showBookmarks?filtered[0]:null;
  const startIdx=page===1&&hero?1:(page-1)*PER_PAGE;
  const paged=filtered.slice(startIdx,startIdx+PER_PAGE);
  const catC={all:articles.length};articles.forEach(a=>{catC[a.category]=(catC[a.category]||0)+1;});
  const bookmarkCount=articles.filter(a=>a.bookmarked).length;

  return(<div style={{minHeight:"100vh",background:"#0a0c12"}}>
    <style>{`@import url('https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;600;700;800&display=swap');*,*::before,*::after{box-sizing:border-box;margin:0;padding:0;}body{background:#0a0c12;color:#c8cdd8;font-family:system-ui,-apple-system,sans-serif;-webkit-font-smoothing:antialiased;}::-webkit-scrollbar{width:4px;}::-webkit-scrollbar-thumb{background:#1e2535;border-radius:2px;}@keyframes fadeUp{from{opacity:0;transform:translateY(20px);}to{opacity:1;transform:translateY(0);}}@keyframes heroIn{from{opacity:0;transform:scale(.96);}to{opacity:1;transform:scale(1);}}@keyframes spin{to{transform:rotate(360deg);}}@keyframes pulse{0%,100%{opacity:1;}50%{opacity:.35;}}input:focus,textarea:focus{border-color:#3b82f6!important;box-shadow:0 0 0 3px rgba(59,130,246,.12)!important;}button:active{transform:scale(.97)!important;}`}</style>
    <Nav pg={pg} setPg={setPg}/>
    {pg!=="Home"?<StaticPage type={pg}/>:<>
      <TrendingBar articles={articles}/>
      <div style={{maxWidth:920,margin:"0 auto",padding:"22px 20px 0"}}>
        <div style={{display:"flex",alignItems:"center",justifyContent:"space-between",marginBottom:16,flexWrap:"wrap",gap:8}}>
          <div><h2 style={{fontSize:28,fontWeight:800,color:"#eef0f6",fontFamily:"'Playfair Display',serif",letterSpacing:-.5}}>Today's AI Intelligence</h2>
            <p style={{fontSize:12,color:"#4a5568",marginTop:4,display:"flex",alignItems:"center",gap:8}}>
              <span style={{width:6,height:6,borderRadius:"50%",background:"#22c55e",boxShadow:"0 0 6px #22c55e55",display:"inline-block",animation:"pulse 2s ease infinite"}}/>
              <span>{articles.length} articles</span>
              {syncing&&<><span style={{width:12,height:12,border:"2px solid #1e2535",borderTopColor:"#3b82f6",borderRadius:"50%",display:"inline-block",animation:"spin .7s linear infinite"}}/><span>Updating…</span></>}
            </p></div>
          <button onClick={()=>{setShowBookmarks(!showBookmarks);setCat("all");}} style={{padding:"7px 16px",borderRadius:9,border:"1px solid",borderColor:showBookmarks?"#fbbf24":"#1c2030",background:showBookmarks?"rgba(251,191,36,.08)":"transparent",color:showBookmarks?"#fbbf24":"#5b6578",fontSize:13,fontWeight:600,cursor:"pointer",transition:"all .25s"}}>★ Saved{bookmarkCount>0&&` (${bookmarkCount})`}</button>
        </div>
        <div style={{position:"relative",marginBottom:14}}><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search articles, topics, or sources…" style={{width:"100%",padding:"12px 16px 12px 42px",borderRadius:13,border:"1.5px solid #1c2233",background:"#10141c",color:"#c8cdd8",fontSize:14,outline:"none",transition:"all .25s",fontWeight:500}}/><svg style={{position:"absolute",left:15,top:"50%",transform:"translateY(-50%)",width:15,height:15}} fill="none" viewBox="0 0 24 24" stroke="#4a5568" strokeWidth={2}><circle cx={11} cy={11} r={8}/><path d="M21 21l-4.35-4.35"/></svg>{search&&<button onClick={()=>setSearch("")} style={{position:"absolute",right:12,top:"50%",transform:"translateY(-50%)",width:24,height:24,borderRadius:"50%",border:"none",background:"#1e2535",color:"#8b95a5",fontSize:11,cursor:"pointer",display:"flex",alignItems:"center",justifyContent:"center"}}>✕</button>}</div>
        {!showBookmarks&&<div style={{display:"flex",gap:5,overflowX:"auto",paddingBottom:16,scrollbarWidth:"none",WebkitOverflowScrolling:"touch"}}>{CATEGORIES.map(c=><button key={c.id} onClick={()=>setCat(c.id)} style={{padding:"7px 16px",borderRadius:11,whiteSpace:"nowrap",border:"1.5px solid",borderColor:cat===c.id?"#3b82f6":"#1c2233",background:cat===c.id?"rgba(59,130,246,.1)":"#10141c",color:cat===c.id?"#60a5fa":"#5b6578",fontSize:12,fontWeight:600,cursor:"pointer",transition:"all .25s",display:"flex",alignItems:"center",gap:5}}>{c.label}{(catC[c.id]||0)>0&&<span style={{fontSize:10,fontWeight:700,color:cat===c.id?"#93bbfc":"#3d4555",background:cat===c.id?"rgba(59,130,246,.12)":"#181d28",padding:"1px 6px",borderRadius:7}}>{catC[c.id]}</span>}</button>)}</div>}
      </div>
      <main style={{maxWidth:920,margin:"0 auto",padding:"0 20px 50px"}}>
        {filtered.length===0?<div style={{textAlign:"center",padding:"60px 20px",animation:"fadeUp .3s ease"}}><div style={{fontSize:40,marginBottom:12,opacity:.2}}>{showBookmarks?"★":"🔍"}</div><p style={{fontSize:16,fontWeight:600,color:"#8b95a5"}}>{showBookmarks?"No saved articles yet":"No articles found"}</p><p style={{fontSize:13,color:"#4a5568",marginTop:4}}>{showBookmarks?"Tap the ☆ icon on any article to save it":"Try a different search or category"}</p></div>:<>
          {hero&&<div style={{marginBottom:22}}><HeroCard item={hero} onBookmark={toggleBookmark}/></div>}
          <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(min(100%,400px),1fr))",gap:18}} key={`${page}-${cat}-${showBookmarks}`}>{paged.map((it,i)=><Card key={it.id} item={it} idx={i} onBookmark={toggleBookmark}/>)}</div>
          <Pages total={filtered.length} page={page} set={p=>{setPage(p);window.scrollTo({top:0,behavior:"smooth"});}}/>
        </>}
      </main>
      <footer style={{borderTop:"1px solid #181d28",padding:"24px 20px",textAlign:"center"}}><p style={{fontSize:11,color:"#1e2535"}}>AI Pulse © 2026 — Live AI intelligence feed — Free forever</p></footer>
    </>}
  </div>);
}
